services:
  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./proxy_data:/data
      - ./proxy_letsencrypt:/etc/letsencrypt
    networks:
      - app-network
        
  family-site:
    image: nginx:alpine
    container_name: dabrion-web
    restart: unless-stopped
    volumes:
      - ${WEBSITE_PATH}:/usr/share/nginx/html:ro
    networks:
      - app-network


  db:
    image: mariadb:10.11
    container_name: nextcloud-db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
    networks:
      - app-network

  nextcloud:
    image: nextcloud:apache
    container_name: nextcloud
    restart: unless-stopped
    expose:
      - "80"
    depends_on:
      - db
    environment:
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_HOST=${MYSQL_HOST}
        #- OVERWRITEWEBROOT=/nextcloud
      - OVERWRITEPROTOCOL=https
        #- NEXTCLOUD_TRUSTED_DOMAINS=marion-alexandre.freeboxos.fr
      - NEXTCLOUD_TRUSTED_DOMAINS=marion-alexandre.freeboxos.fr 192.168.1.34
    volumes:
      - ./nextcloud_config:/var/www/html
      - ${NC_DATA_PATH}:/var/www/html/data
      - ${HOMES_PATH}:/host_homes
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
